---
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- debug: 
    msg: "{{ deb_architecture.stdout }}"

- name: 'Include geerlingguy.docker'
  include_role:
    name: 'geerlingguy.docker'
  vars:
    docker_apt_arch: "{{ deb_architecture.stdout }}"

- name: install docker pip
  pip:
    name: docker

- name: Start ROS master docker container
  docker_container:
    name: '{{ docker_name }}'
    image: 'frankjoshua/ros-master:{{ cpu_arch }}'
    network_mode: 'host'
    restart_policy: 'unless-stopped'
    env:
      ROS_MASTER_URI: '{{ ros_master_uri }}'
      ROS_IP: '{{ ros_ip }}'
