---
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- debug:
    msg: '{{ deb_architecture.stdout }}'

- name: Install Docker
  import_tasks: docker.yml
  vars:
    docker_apt_arch: '{{ deb_architecture.stdout }}'

- name: Install Pip
  package:
    name: python3-pip
    state: present

- name: install docker pip
  pip:
    name: docker

- name: Ensure docker deamon is running
  shell: service docker start
  ignore_errors: yes
  changed_when: false

- name: Start ROS master docker container
  docker_container:
    name: '{{ docker_name }}'
    image: 'frankjoshua/ros-master'
    network_mode: 'host'
    restart_policy: 'unless-stopped'
    env:
      ROS_MASTER_URI: '{{ ros_master_uri }}'
      ROS_IP: '{{ ros_ip }}'
