---
- name: Cleanup
  hosts: all
  gather_facts: no
  ignore_errors: true
  ignore_unreachable: true
  tasks:
    - name: Remove container
      docker_container:
        name: "{{ lookup('env', 'DOCKER_NAME') }}"
        state: absent
