---
- name: Verify
  hosts: all

  vars:
    container_name: "{{ lookup('env', 'DOCKER_NAME') }}"

  tasks:
    - name: Wait for container to start
      wait_for:
        timeout: 30

    - name: Get infos on container
      docker_container_info:
        name: '{{ container_name }}'
      register: result

    - name: Does container exist?
      assert:
        that: result.exists

    - name: Check if container is healthy
      assert:
        that: "'{{ result.container['State']['Health']['Status'] }}' == 'healthy'"
      when: result.exists
