---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Get infos on container
      docker_container_info:
        name: ros_master
      register: result

    - name: Does container exist?
      assert:
        that: result.exists

    - name: Check if container is healthy
      assert:
        that: "'{{ result.container['State']['Health']['Status'] }}' == 'healthy'"
      when: result.exists
      retries: 3
      delay: 15
